FROM golang:latest

WORKDIR /app
#Copio todo lo que esta en el directorio actual
COPY . .


#Ejecuto el siguiente comando. Nos aseguramos que todas las dependencias esten alineadas
RUN go mod tidy
#Construyo el binario
RUN go build -o logistica

#Facciones no escucha peticiones, por ende no necesita exponer un puerto

#Ejecuto el build creado
CMD ["./facciones"]