// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: servidores_regionales.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServidorRegionalService_EnviarEstado_FullMethodName = "/servidoresregionales.ServidorRegionalService/EnviarEstado"
)

// ServidorRegionalServiceClient is the client API for ServidorRegionalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServidorRegionalServiceClient interface {
	// RPC para enviar el estado de un Digimon al Primary Node
	EnviarEstado(ctx context.Context, in *EstadoDigimon, opts ...grpc.CallOption) (*Confirmacion, error)
}

type servidorRegionalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServidorRegionalServiceClient(cc grpc.ClientConnInterface) ServidorRegionalServiceClient {
	return &servidorRegionalServiceClient{cc}
}

func (c *servidorRegionalServiceClient) EnviarEstado(ctx context.Context, in *EstadoDigimon, opts ...grpc.CallOption) (*Confirmacion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Confirmacion)
	err := c.cc.Invoke(ctx, ServidorRegionalService_EnviarEstado_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServidorRegionalServiceServer is the server API for ServidorRegionalService service.
// All implementations must embed UnimplementedServidorRegionalServiceServer
// for forward compatibility.
type ServidorRegionalServiceServer interface {
	// RPC para enviar el estado de un Digimon al Primary Node
	EnviarEstado(context.Context, *EstadoDigimon) (*Confirmacion, error)
	mustEmbedUnimplementedServidorRegionalServiceServer()
}

// UnimplementedServidorRegionalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServidorRegionalServiceServer struct{}

func (UnimplementedServidorRegionalServiceServer) EnviarEstado(context.Context, *EstadoDigimon) (*Confirmacion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarEstado not implemented")
}
func (UnimplementedServidorRegionalServiceServer) mustEmbedUnimplementedServidorRegionalServiceServer() {
}
func (UnimplementedServidorRegionalServiceServer) testEmbeddedByValue() {}

// UnsafeServidorRegionalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServidorRegionalServiceServer will
// result in compilation errors.
type UnsafeServidorRegionalServiceServer interface {
	mustEmbedUnimplementedServidorRegionalServiceServer()
}

func RegisterServidorRegionalServiceServer(s grpc.ServiceRegistrar, srv ServidorRegionalServiceServer) {
	// If the following call pancis, it indicates UnimplementedServidorRegionalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServidorRegionalService_ServiceDesc, srv)
}

func _ServidorRegionalService_EnviarEstado_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstadoDigimon)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServidorRegionalServiceServer).EnviarEstado(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServidorRegionalService_EnviarEstado_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServidorRegionalServiceServer).EnviarEstado(ctx, req.(*EstadoDigimon))
	}
	return interceptor(ctx, in, info, handler)
}

// ServidorRegionalService_ServiceDesc is the grpc.ServiceDesc for ServidorRegionalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServidorRegionalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servidoresregionales.ServidorRegionalService",
	HandlerType: (*ServidorRegionalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnviarEstado",
			Handler:    _ServidorRegionalService_EnviarEstado_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "servidores_regionales.proto",
}
