// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: diaboromon.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiaboromonService_Atacar_FullMethodName = "/diaboromon.DiaboromonService/Atacar"
)

// DiaboromonServiceClient is the client API for DiaboromonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiaboromonServiceClient interface {
	// RPC para atacar al Nodo Tai
	Atacar(ctx context.Context, in *Ataque, opts ...grpc.CallOption) (*Confirmacion, error)
}

type diaboromonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiaboromonServiceClient(cc grpc.ClientConnInterface) DiaboromonServiceClient {
	return &diaboromonServiceClient{cc}
}

func (c *diaboromonServiceClient) Atacar(ctx context.Context, in *Ataque, opts ...grpc.CallOption) (*Confirmacion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Confirmacion)
	err := c.cc.Invoke(ctx, DiaboromonService_Atacar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiaboromonServiceServer is the server API for DiaboromonService service.
// All implementations must embed UnimplementedDiaboromonServiceServer
// for forward compatibility.
type DiaboromonServiceServer interface {
	// RPC para atacar al Nodo Tai
	Atacar(context.Context, *Ataque) (*Confirmacion, error)
	mustEmbedUnimplementedDiaboromonServiceServer()
}

// UnimplementedDiaboromonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiaboromonServiceServer struct{}

func (UnimplementedDiaboromonServiceServer) Atacar(context.Context, *Ataque) (*Confirmacion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Atacar not implemented")
}
func (UnimplementedDiaboromonServiceServer) mustEmbedUnimplementedDiaboromonServiceServer() {}
func (UnimplementedDiaboromonServiceServer) testEmbeddedByValue()                           {}

// UnsafeDiaboromonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiaboromonServiceServer will
// result in compilation errors.
type UnsafeDiaboromonServiceServer interface {
	mustEmbedUnimplementedDiaboromonServiceServer()
}

func RegisterDiaboromonServiceServer(s grpc.ServiceRegistrar, srv DiaboromonServiceServer) {
	// If the following call pancis, it indicates UnimplementedDiaboromonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiaboromonService_ServiceDesc, srv)
}

func _DiaboromonService_Atacar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ataque)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaboromonServiceServer).Atacar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaboromonService_Atacar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaboromonServiceServer).Atacar(ctx, req.(*Ataque))
	}
	return interceptor(ctx, in, info, handler)
}

// DiaboromonService_ServiceDesc is the grpc.ServiceDesc for DiaboromonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiaboromonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "diaboromon.DiaboromonService",
	HandlerType: (*DiaboromonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Atacar",
			Handler:    _DiaboromonService_Atacar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "diaboromon.proto",
}
