// primary_node.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: primary_node.proto

package primary_reg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrimaryNodeService_RecibirDatosRegional_FullMethodName = "/primarynode.PrimaryNodeService/RecibirDatosRegional"
)

// PrimaryNodeServiceClient is the client API for PrimaryNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio para el Primary Node que recibe datos de los servidores regionales
type PrimaryNodeServiceClient interface {
	// RPC para recibir la información cifrada de los servidores regionales
	RecibirDatosRegional(ctx context.Context, in *DatosCifradosDigimon, opts ...grpc.CallOption) (*Confirmacion, error)
}

type primaryNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimaryNodeServiceClient(cc grpc.ClientConnInterface) PrimaryNodeServiceClient {
	return &primaryNodeServiceClient{cc}
}

func (c *primaryNodeServiceClient) RecibirDatosRegional(ctx context.Context, in *DatosCifradosDigimon, opts ...grpc.CallOption) (*Confirmacion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Confirmacion)
	err := c.cc.Invoke(ctx, PrimaryNodeService_RecibirDatosRegional_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrimaryNodeServiceServer is the server API for PrimaryNodeService service.
// All implementations must embed UnimplementedPrimaryNodeServiceServer
// for forward compatibility.
//
// Servicio para el Primary Node que recibe datos de los servidores regionales
type PrimaryNodeServiceServer interface {
	// RPC para recibir la información cifrada de los servidores regionales
	RecibirDatosRegional(context.Context, *DatosCifradosDigimon) (*Confirmacion, error)
	mustEmbedUnimplementedPrimaryNodeServiceServer()
}

// UnimplementedPrimaryNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrimaryNodeServiceServer struct{}

func (UnimplementedPrimaryNodeServiceServer) RecibirDatosRegional(context.Context, *DatosCifradosDigimon) (*Confirmacion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecibirDatosRegional not implemented")
}
func (UnimplementedPrimaryNodeServiceServer) mustEmbedUnimplementedPrimaryNodeServiceServer() {}
func (UnimplementedPrimaryNodeServiceServer) testEmbeddedByValue()                            {}

// UnsafePrimaryNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrimaryNodeServiceServer will
// result in compilation errors.
type UnsafePrimaryNodeServiceServer interface {
	mustEmbedUnimplementedPrimaryNodeServiceServer()
}

func RegisterPrimaryNodeServiceServer(s grpc.ServiceRegistrar, srv PrimaryNodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedPrimaryNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrimaryNodeService_ServiceDesc, srv)
}

func _PrimaryNodeService_RecibirDatosRegional_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatosCifradosDigimon)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimaryNodeServiceServer).RecibirDatosRegional(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrimaryNodeService_RecibirDatosRegional_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimaryNodeServiceServer).RecibirDatosRegional(ctx, req.(*DatosCifradosDigimon))
	}
	return interceptor(ctx, in, info, handler)
}

// PrimaryNodeService_ServiceDesc is the grpc.ServiceDesc for PrimaryNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrimaryNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "primarynode.PrimaryNodeService",
	HandlerType: (*PrimaryNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecibirDatosRegional",
			Handler:    _PrimaryNodeService_RecibirDatosRegional_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "primary_node.proto",
}
