build:
    docker-compose build
# Comando para iniciar el servicio de Logística (Konzu)
docker-logistica: build
	docker-compose -f ./app/docker-compose.yml up logistica

# Comando para iniciar el servicio de Finanzas (Raquis)
docker-finanzas: build
	docker-compose -f ./app/docker-compose.yml up finanzas

# Comando para iniciar el servicio de Caravanas
docker-caravanas: build
	docker-compose -f ./app/docker-compose.yml up caravanas

# Comando para iniciar el servicio de Clientes( Clientes  Se usa indistintamente con facciones)
docker-clientes: build
	docker-compose -f ./app/docker-compose.yml up facciones