// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: jayce-broker.proto

package jayce_broker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Estado de la respuesta
type ResponseStatus int32

const (
	ResponseStatus_OK    ResponseStatus = 0
	ResponseStatus_ERROR ResponseStatus = 1
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	ResponseStatus_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_jayce_broker_proto_enumTypes[0].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_jayce_broker_proto_enumTypes[0]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_jayce_broker_proto_rawDescGZIP(), []int{0}
}

// Mensaje de solicitud enviado desde Jayce al Broker
type JayceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Nombre de la región a consultar (ej. Noxus)
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// Nombre del producto a consultar (ej. Vino)
	ProductName string `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
}

func (x *JayceRequest) Reset() {
	*x = JayceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jayce_broker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JayceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JayceRequest) ProtoMessage() {}

func (x *JayceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jayce_broker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JayceRequest.ProtoReflect.Descriptor instead.
func (*JayceRequest) Descriptor() ([]byte, []int) {
	return file_jayce_broker_proto_rawDescGZIP(), []int{0}
}

func (x *JayceRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *JayceRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

// Mensaje de respuesta enviado desde el Broker a Jayce
type JayceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Estado de la respuesta: OK o ERROR
	Status ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=jaycebroker.ResponseStatus" json:"status,omitempty"`
	// Reloj vectorial asociado al registro, usado para Monotonic Reads
	VectorClock *VectorClock `protobuf:"bytes,2,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
	// Mensaje opcional en caso de error
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *JayceResponse) Reset() {
	*x = JayceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jayce_broker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JayceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JayceResponse) ProtoMessage() {}

func (x *JayceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jayce_broker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JayceResponse.ProtoReflect.Descriptor instead.
func (*JayceResponse) Descriptor() ([]byte, []int) {
	return file_jayce_broker_proto_rawDescGZIP(), []int{1}
}

func (x *JayceResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_OK
}

func (x *JayceResponse) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

func (x *JayceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Reloj vectorial que representa la versión de los datos en los servidores
type VectorClock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server1 int32 `protobuf:"varint,1,opt,name=server1,proto3" json:"server1,omitempty"` // Contador de cambios en Servidor Hextech 1
	Server2 int32 `protobuf:"varint,2,opt,name=server2,proto3" json:"server2,omitempty"` // Contador de cambios en Servidor Hextech 2
	Server3 int32 `protobuf:"varint,3,opt,name=server3,proto3" json:"server3,omitempty"` // Contador de cambios en Servidor Hextech 3
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jayce_broker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_jayce_broker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_jayce_broker_proto_rawDescGZIP(), []int{2}
}

func (x *VectorClock) GetServer1() int32 {
	if x != nil {
		return x.Server1
	}
	return 0
}

func (x *VectorClock) GetServer2() int32 {
	if x != nil {
		return x.Server2
	}
	return 0
}

func (x *VectorClock) GetServer3() int32 {
	if x != nil {
		return x.Server3
	}
	return 0
}

var File_jayce_broker_proto protoreflect.FileDescriptor

var file_jayce_broker_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6a, 0x61, 0x79, 0x63, 0x65, 0x2d, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6a, 0x61, 0x79, 0x63, 0x65, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x22, 0x49, 0x0a, 0x0c, 0x4a, 0x61, 0x79, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x9b, 0x01, 0x0a,
	0x0d, 0x4a, 0x61, 0x79, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b,
	0x2e, 0x6a, 0x61, 0x79, 0x63, 0x65, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x3b, 0x0a, 0x0c, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x63, 0x6c,
	0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6a, 0x61, 0x79, 0x63,
	0x65, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x0b, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5b, 0x0a, 0x0b, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x32, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x32, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x33, 0x2a, 0x23, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x32, 0x5e, 0x0a, 0x12,
	0x4a, 0x61, 0x79, 0x63, 0x65, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x48, 0x0a, 0x0f, 0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x6f, 0x12, 0x19, 0x2e, 0x6a, 0x61, 0x79, 0x63, 0x65, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x61, 0x79, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x6a, 0x61, 0x79, 0x63, 0x65, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x4a,
	0x61, 0x79, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x6a, 0x61, 0x79, 0x63, 0x65, 0x2d, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jayce_broker_proto_rawDescOnce sync.Once
	file_jayce_broker_proto_rawDescData = file_jayce_broker_proto_rawDesc
)

func file_jayce_broker_proto_rawDescGZIP() []byte {
	file_jayce_broker_proto_rawDescOnce.Do(func() {
		file_jayce_broker_proto_rawDescData = protoimpl.X.CompressGZIP(file_jayce_broker_proto_rawDescData)
	})
	return file_jayce_broker_proto_rawDescData
}

var file_jayce_broker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jayce_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_jayce_broker_proto_goTypes = []any{
	(ResponseStatus)(0),   // 0: jaycebroker.ResponseStatus
	(*JayceRequest)(nil),  // 1: jaycebroker.JayceRequest
	(*JayceResponse)(nil), // 2: jaycebroker.JayceResponse
	(*VectorClock)(nil),   // 3: jaycebroker.VectorClock
}
var file_jayce_broker_proto_depIdxs = []int32{
	0, // 0: jaycebroker.JayceResponse.status:type_name -> jaycebroker.ResponseStatus
	3, // 1: jaycebroker.JayceResponse.vector_clock:type_name -> jaycebroker.VectorClock
	1, // 2: jaycebroker.JayceBrokerService.ObtenerProducto:input_type -> jaycebroker.JayceRequest
	2, // 3: jaycebroker.JayceBrokerService.ObtenerProducto:output_type -> jaycebroker.JayceResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_jayce_broker_proto_init() }
func file_jayce_broker_proto_init() {
	if File_jayce_broker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jayce_broker_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*JayceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jayce_broker_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*JayceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jayce_broker_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*VectorClock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jayce_broker_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jayce_broker_proto_goTypes,
		DependencyIndexes: file_jayce_broker_proto_depIdxs,
		EnumInfos:         file_jayce_broker_proto_enumTypes,
		MessageInfos:      file_jayce_broker_proto_msgTypes,
	}.Build()
	File_jayce_broker_proto = out.File
	file_jayce_broker_proto_rawDesc = nil
	file_jayce_broker_proto_goTypes = nil
	file_jayce_broker_proto_depIdxs = nil
}
