// data_node.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: primary-data.proto

package primary_data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensaje para enviar datos procesados a los Data Nodes
type DatosParaDataNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`            // ID del Digimon
	Atributo string `protobuf:"bytes,2,opt,name=atributo,proto3" json:"atributo,omitempty"` // Atributo del Digimon (Data, Vaccine, Virus)
}

func (x *DatosParaDataNode) Reset() {
	*x = DatosParaDataNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primary_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DatosParaDataNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatosParaDataNode) ProtoMessage() {}

func (x *DatosParaDataNode) ProtoReflect() protoreflect.Message {
	mi := &file_primary_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatosParaDataNode.ProtoReflect.Descriptor instead.
func (*DatosParaDataNode) Descriptor() ([]byte, []int) {
	return file_primary_data_proto_rawDescGZIP(), []int{0}
}

func (x *DatosParaDataNode) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DatosParaDataNode) GetAtributo() string {
	if x != nil {
		return x.Atributo
	}
	return ""
}

// Mensaje de confirmación de recepción para el Primary Node
type Confirmacion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"` // Mensaje de confirmación del Data Node
}

func (x *Confirmacion) Reset() {
	*x = Confirmacion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primary_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirmacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmacion) ProtoMessage() {}

func (x *Confirmacion) ProtoReflect() protoreflect.Message {
	mi := &file_primary_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmacion.ProtoReflect.Descriptor instead.
func (*Confirmacion) Descriptor() ([]byte, []int) {
	return file_primary_data_proto_rawDescGZIP(), []int{1}
}

func (x *Confirmacion) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// Mensaje para la solicitud de datos del Primary Node
type SolicitudDatos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ID del Digimon solicitado
}

func (x *SolicitudDatos) Reset() {
	*x = SolicitudDatos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primary_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudDatos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudDatos) ProtoMessage() {}

func (x *SolicitudDatos) ProtoReflect() protoreflect.Message {
	mi := &file_primary_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudDatos.ProtoReflect.Descriptor instead.
func (*SolicitudDatos) Descriptor() ([]byte, []int) {
	return file_primary_data_proto_rawDescGZIP(), []int{2}
}

func (x *SolicitudDatos) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Mensaje de respuesta con el atributo del Digimon solicitado
type RespuestaDatos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Atributo string `protobuf:"bytes,1,opt,name=atributo,proto3" json:"atributo,omitempty"` // Atributo del Digimon (Data, Vaccine, Virus)
}

func (x *RespuestaDatos) Reset() {
	*x = RespuestaDatos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primary_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaDatos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaDatos) ProtoMessage() {}

func (x *RespuestaDatos) ProtoReflect() protoreflect.Message {
	mi := &file_primary_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaDatos.ProtoReflect.Descriptor instead.
func (*RespuestaDatos) Descriptor() ([]byte, []int) {
	return file_primary_data_proto_rawDescGZIP(), []int{3}
}

func (x *RespuestaDatos) GetAtributo() string {
	if x != nil {
		return x.Atributo
	}
	return ""
}

var File_primary_data_proto protoreflect.FileDescriptor

var file_primary_data_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x3f,
	0x0a, 0x11, 0x44, 0x61, 0x74, 0x6f, 0x73, 0x50, 0x61, 0x72, 0x61, 0x44, 0x61, 0x74, 0x61, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x6f, 0x22,
	0x28, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x53, 0x6f, 0x6c,
	0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x44, 0x61, 0x74, 0x6f, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x0e, 0x52,
	0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x44, 0x61, 0x74, 0x6f, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x6f, 0x32, 0x9a, 0x01, 0x0a, 0x0f, 0x44, 0x61,
	0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a,
	0x0c, 0x47, 0x75, 0x61, 0x72, 0x64, 0x61, 0x72, 0x44, 0x61, 0x74, 0x6f, 0x73, 0x12, 0x1b, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x6f, 0x73, 0x50, 0x61,
	0x72, 0x61, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x1a, 0x16, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x63, 0x69,
	0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x0c, 0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x6f, 0x73, 0x12, 0x18, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x53, 0x6f,
	0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x44, 0x61, 0x74, 0x6f, 0x73, 0x1a, 0x18, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74,
	0x61, 0x44, 0x61, 0x74, 0x6f, 0x73, 0x42, 0x13, 0x5a, 0x11, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_primary_data_proto_rawDescOnce sync.Once
	file_primary_data_proto_rawDescData = file_primary_data_proto_rawDesc
)

func file_primary_data_proto_rawDescGZIP() []byte {
	file_primary_data_proto_rawDescOnce.Do(func() {
		file_primary_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_primary_data_proto_rawDescData)
	})
	return file_primary_data_proto_rawDescData
}

var file_primary_data_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_primary_data_proto_goTypes = []any{
	(*DatosParaDataNode)(nil), // 0: datanode.DatosParaDataNode
	(*Confirmacion)(nil),      // 1: datanode.Confirmacion
	(*SolicitudDatos)(nil),    // 2: datanode.SolicitudDatos
	(*RespuestaDatos)(nil),    // 3: datanode.RespuestaDatos
}
var file_primary_data_proto_depIdxs = []int32{
	0, // 0: datanode.DataNodeService.GuardarDatos:input_type -> datanode.DatosParaDataNode
	2, // 1: datanode.DataNodeService.ObtenerDatos:input_type -> datanode.SolicitudDatos
	1, // 2: datanode.DataNodeService.GuardarDatos:output_type -> datanode.Confirmacion
	3, // 3: datanode.DataNodeService.ObtenerDatos:output_type -> datanode.RespuestaDatos
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_primary_data_proto_init() }
func file_primary_data_proto_init() {
	if File_primary_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_primary_data_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DatosParaDataNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_primary_data_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Confirmacion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_primary_data_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SolicitudDatos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_primary_data_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RespuestaDatos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_primary_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_primary_data_proto_goTypes,
		DependencyIndexes: file_primary_data_proto_depIdxs,
		MessageInfos:      file_primary_data_proto_msgTypes,
	}.Build()
	File_primary_data_proto = out.File
	file_primary_data_proto_rawDesc = nil
	file_primary_data_proto_goTypes = nil
	file_primary_data_proto_depIdxs = nil
}
