# Comando para iniciar el servicio de Broker
docker-broker:
	@docker-compose -f ./app/docker-compose.yml up broker

# Comando para iniciar el servicio de Supervisores
docker-supervisores:
	@docker-compose -f ./app/docker-compose.yml up supervisores
