version: '3'
services:
  logistica:
    build: ./logistica
    container_name: container_logistica
    ports:
      - "50051:50051"
    depends_on:
      - rabbitmq
    networks:
      - network_tarea
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - network_tarea
  caravanas:
    build: ./caravanas
    container_name: container_caravanas
    ports:
      - "50052:50052"
    networks:
      - network_tarea
    #enviorment: Variables de entorno
    environment:
      - SERVER_HOST=container_logistica
  facciones:
    build: ./facciones
    container_name: container_facciones
    networks:
      - network_tarea
  finanzas:
    build: ./finanzas
    container_name: container_finanzas
    networks:
      - network_tarea
#Red EXTERNA que se crea mediante docker
networks:
  network_tarea:
    external: true
    

