// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: jayce-server.proto

package jayce_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JayceServerService_ObtenerProducto_FullMethodName = "/jayceserver.JayceServerService/ObtenerProducto"
)

// JayceServerServiceClient is the client API for JayceServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JayceServerServiceClient interface {
	ObtenerProducto(ctx context.Context, in *JayceRequest, opts ...grpc.CallOption) (*JayceResponse, error)
}

type jayceServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJayceServerServiceClient(cc grpc.ClientConnInterface) JayceServerServiceClient {
	return &jayceServerServiceClient{cc}
}

func (c *jayceServerServiceClient) ObtenerProducto(ctx context.Context, in *JayceRequest, opts ...grpc.CallOption) (*JayceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JayceResponse)
	err := c.cc.Invoke(ctx, JayceServerService_ObtenerProducto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JayceServerServiceServer is the server API for JayceServerService service.
// All implementations must embed UnimplementedJayceServerServiceServer
// for forward compatibility.
type JayceServerServiceServer interface {
	ObtenerProducto(context.Context, *JayceRequest) (*JayceResponse, error)
	mustEmbedUnimplementedJayceServerServiceServer()
}

// UnimplementedJayceServerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJayceServerServiceServer struct{}

func (UnimplementedJayceServerServiceServer) ObtenerProducto(context.Context, *JayceRequest) (*JayceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerProducto not implemented")
}
func (UnimplementedJayceServerServiceServer) mustEmbedUnimplementedJayceServerServiceServer() {}
func (UnimplementedJayceServerServiceServer) testEmbeddedByValue()                            {}

// UnsafeJayceServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JayceServerServiceServer will
// result in compilation errors.
type UnsafeJayceServerServiceServer interface {
	mustEmbedUnimplementedJayceServerServiceServer()
}

func RegisterJayceServerServiceServer(s grpc.ServiceRegistrar, srv JayceServerServiceServer) {
	// If the following call pancis, it indicates UnimplementedJayceServerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JayceServerService_ServiceDesc, srv)
}

func _JayceServerService_ObtenerProducto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JayceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JayceServerServiceServer).ObtenerProducto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JayceServerService_ObtenerProducto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JayceServerServiceServer).ObtenerProducto(ctx, req.(*JayceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JayceServerService_ServiceDesc is the grpc.ServiceDesc for JayceServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JayceServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jayceserver.JayceServerService",
	HandlerType: (*JayceServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ObtenerProducto",
			Handler:    _JayceServerService_ObtenerProducto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jayce-server.proto",
}
