// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: jayce-server.proto

package jayce_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JayceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region      string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	ProductName string `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
}

func (x *JayceRequest) Reset() {
	*x = JayceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jayce_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JayceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JayceRequest) ProtoMessage() {}

func (x *JayceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jayce_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JayceRequest.ProtoReflect.Descriptor instead.
func (*JayceRequest) Descriptor() ([]byte, []int) {
	return file_jayce_server_proto_rawDescGZIP(), []int{0}
}

func (x *JayceRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *JayceRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

type JayceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cantidad    int32        `protobuf:"varint,1,opt,name=cantidad,proto3" json:"cantidad,omitempty"`
	VectorClock *VectorClock `protobuf:"bytes,2,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
}

func (x *JayceResponse) Reset() {
	*x = JayceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jayce_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JayceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JayceResponse) ProtoMessage() {}

func (x *JayceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jayce_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JayceResponse.ProtoReflect.Descriptor instead.
func (*JayceResponse) Descriptor() ([]byte, []int) {
	return file_jayce_server_proto_rawDescGZIP(), []int{1}
}

func (x *JayceResponse) GetCantidad() int32 {
	if x != nil {
		return x.Cantidad
	}
	return 0
}

func (x *JayceResponse) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type VectorClock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server1 int32 `protobuf:"varint,1,opt,name=server1,proto3" json:"server1,omitempty"`
	Server2 int32 `protobuf:"varint,2,opt,name=server2,proto3" json:"server2,omitempty"`
	Server3 int32 `protobuf:"varint,3,opt,name=server3,proto3" json:"server3,omitempty"`
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jayce_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_jayce_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_jayce_server_proto_rawDescGZIP(), []int{2}
}

func (x *VectorClock) GetServer1() int32 {
	if x != nil {
		return x.Server1
	}
	return 0
}

func (x *VectorClock) GetServer2() int32 {
	if x != nil {
		return x.Server2
	}
	return 0
}

func (x *VectorClock) GetServer3() int32 {
	if x != nil {
		return x.Server3
	}
	return 0
}

var File_jayce_server_proto protoreflect.FileDescriptor

var file_jayce_server_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6a, 0x61, 0x79, 0x63, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6a, 0x61, 0x79, 0x63, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x22, 0x49, 0x0a, 0x0c, 0x4a, 0x61, 0x79, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x68, 0x0a, 0x0d,
	0x4a, 0x61, 0x79, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x63, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x12, 0x3b, 0x0a, 0x0c, 0x76, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x5f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6a, 0x61, 0x79, 0x63, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0b, 0x76, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x5b, 0x0a, 0x0b, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x31, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x32, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x33, 0x32, 0x5e, 0x0a, 0x12, 0x4a, 0x61, 0x79, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0f, 0x4f, 0x62, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x12, 0x19, 0x2e, 0x6a,
	0x61, 0x79, 0x63, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x61, 0x79, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6a, 0x61, 0x79, 0x63, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x61, 0x79, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6a, 0x61, 0x79, 0x63,
	0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jayce_server_proto_rawDescOnce sync.Once
	file_jayce_server_proto_rawDescData = file_jayce_server_proto_rawDesc
)

func file_jayce_server_proto_rawDescGZIP() []byte {
	file_jayce_server_proto_rawDescOnce.Do(func() {
		file_jayce_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_jayce_server_proto_rawDescData)
	})
	return file_jayce_server_proto_rawDescData
}

var file_jayce_server_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_jayce_server_proto_goTypes = []any{
	(*JayceRequest)(nil),  // 0: jayceserver.JayceRequest
	(*JayceResponse)(nil), // 1: jayceserver.JayceResponse
	(*VectorClock)(nil),   // 2: jayceserver.VectorClock
}
var file_jayce_server_proto_depIdxs = []int32{
	2, // 0: jayceserver.JayceResponse.vector_clock:type_name -> jayceserver.VectorClock
	0, // 1: jayceserver.JayceServerService.ObtenerProducto:input_type -> jayceserver.JayceRequest
	1, // 2: jayceserver.JayceServerService.ObtenerProducto:output_type -> jayceserver.JayceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jayce_server_proto_init() }
func file_jayce_server_proto_init() {
	if File_jayce_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jayce_server_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*JayceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jayce_server_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*JayceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jayce_server_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*VectorClock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jayce_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jayce_server_proto_goTypes,
		DependencyIndexes: file_jayce_server_proto_depIdxs,
		MessageInfos:      file_jayce_server_proto_msgTypes,
	}.Build()
	File_jayce_server_proto = out.File
	file_jayce_server_proto_rawDesc = nil
	file_jayce_server_proto_goTypes = nil
	file_jayce_server_proto_depIdxs = nil
}
