FROM golang:latest

WORKDIR /app
#Copio todo lo que esta en el directorio actual
COPY . .


#Ejecuto el siguiente comando. Nos aseguramos que todas las dependencias esten alineadas
RUN go mod tidy
#Construyo el binario
RUN go build -o broker

#broker se comporta como servidor,por ende debo exponer el puerto
EXPOSE 50054

#Ejecuto el build creado
CMD ["./broker"]