// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: tai-diaboromon.proto

package tai_diaboromon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensaje de solicitud de ataque de Diaboromon hacia Nodo Tai
type SolicitudAtaque struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"` // Mensaje para indicar ataque ("Diaboromon ataca")
}

func (x *SolicitudAtaque) Reset() {
	*x = SolicitudAtaque{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tai_diaboromon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudAtaque) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudAtaque) ProtoMessage() {}

func (x *SolicitudAtaque) ProtoReflect() protoreflect.Message {
	mi := &file_tai_diaboromon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudAtaque.ProtoReflect.Descriptor instead.
func (*SolicitudAtaque) Descriptor() ([]byte, []int) {
	return file_tai_diaboromon_proto_rawDescGZIP(), []int{0}
}

func (x *SolicitudAtaque) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// Mensaje de confirmación del ataque recibido por Nodo Tai
type ConfirmacionAtaque struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"` // Confirmación de recepción del ataque
}

func (x *ConfirmacionAtaque) Reset() {
	*x = ConfirmacionAtaque{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tai_diaboromon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmacionAtaque) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmacionAtaque) ProtoMessage() {}

func (x *ConfirmacionAtaque) ProtoReflect() protoreflect.Message {
	mi := &file_tai_diaboromon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmacionAtaque.ProtoReflect.Descriptor instead.
func (*ConfirmacionAtaque) Descriptor() ([]byte, []int) {
	return file_tai_diaboromon_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmacionAtaque) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// Mensaje de solicitud del Nodo Tai sobre el estado de la vida restante
type SolicitudEstado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"` // Mensaje solicitando el estado ("Solicitar estado de vida")
}

func (x *SolicitudEstado) Reset() {
	*x = SolicitudEstado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tai_diaboromon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudEstado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudEstado) ProtoMessage() {}

func (x *SolicitudEstado) ProtoReflect() protoreflect.Message {
	mi := &file_tai_diaboromon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudEstado.ProtoReflect.Descriptor instead.
func (*SolicitudEstado) Descriptor() ([]byte, []int) {
	return file_tai_diaboromon_proto_rawDescGZIP(), []int{2}
}

func (x *SolicitudEstado) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// Mensaje de respuesta con la vida actual del Nodo Tai
type RespuestaEstado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VidaRestante int32 `protobuf:"varint,1,opt,name=vida_restante,json=vidaRestante,proto3" json:"vida_restante,omitempty"` // Vida restante de Greymon/Garurumon
}

func (x *RespuestaEstado) Reset() {
	*x = RespuestaEstado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tai_diaboromon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaEstado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaEstado) ProtoMessage() {}

func (x *RespuestaEstado) ProtoReflect() protoreflect.Message {
	mi := &file_tai_diaboromon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaEstado.ProtoReflect.Descriptor instead.
func (*RespuestaEstado) Descriptor() ([]byte, []int) {
	return file_tai_diaboromon_proto_rawDescGZIP(), []int{3}
}

func (x *RespuestaEstado) GetVidaRestante() int32 {
	if x != nil {
		return x.VidaRestante
	}
	return 0
}

var File_tai_diaboromon_proto protoreflect.FileDescriptor

var file_tai_diaboromon_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x61, 0x69, 0x2d, 0x64, 0x69, 0x61, 0x62, 0x6f, 0x72, 0x6f, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x61, 0x69, 0x64, 0x69, 0x61, 0x62, 0x6f,
	0x72, 0x6f, 0x6d, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x0f, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74,
	0x75, 0x64, 0x41, 0x74, 0x61, 0x71, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73,
	0x61, 0x6a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61,
	0x6a, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x63, 0x69,
	0x6f, 0x6e, 0x41, 0x74, 0x61, 0x71, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73,
	0x61, 0x6a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61,
	0x6a, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x45,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x22,
	0x36, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x45, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x69, 0x64, 0x61, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x61,
	0x6e, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x76, 0x69, 0x64, 0x61, 0x52,
	0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x65, 0x32, 0xbb, 0x01, 0x0a, 0x14, 0x54, 0x61, 0x69, 0x44,
	0x69, 0x61, 0x62, 0x6f, 0x72, 0x6f, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x55, 0x0a, 0x10, 0x41, 0x74, 0x61, 0x71, 0x75, 0x65, 0x44, 0x69, 0x61, 0x62, 0x6f, 0x72,
	0x6f, 0x6d, 0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x74, 0x61, 0x69, 0x64, 0x69, 0x61, 0x62, 0x6f, 0x72,
	0x6f, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x41, 0x74,
	0x61, 0x71, 0x75, 0x65, 0x1a, 0x21, 0x2e, 0x74, 0x61, 0x69, 0x64, 0x69, 0x61, 0x62, 0x6f, 0x72,
	0x6f, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x6f,
	0x6e, 0x41, 0x74, 0x61, 0x71, 0x75, 0x65, 0x12, 0x4c, 0x0a, 0x0a, 0x45, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x56, 0x69, 0x64, 0x61, 0x12, 0x1e, 0x2e, 0x74, 0x61, 0x69, 0x64, 0x69, 0x61, 0x62, 0x6f,
	0x72, 0x6f, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x45,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x1a, 0x1e, 0x2e, 0x74, 0x61, 0x69, 0x64, 0x69, 0x61, 0x62, 0x6f,
	0x72, 0x6f, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x45,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x42, 0x15, 0x5a, 0x13, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x61,
	0x69, 0x2d, 0x64, 0x69, 0x61, 0x62, 0x6f, 0x72, 0x6f, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tai_diaboromon_proto_rawDescOnce sync.Once
	file_tai_diaboromon_proto_rawDescData = file_tai_diaboromon_proto_rawDesc
)

func file_tai_diaboromon_proto_rawDescGZIP() []byte {
	file_tai_diaboromon_proto_rawDescOnce.Do(func() {
		file_tai_diaboromon_proto_rawDescData = protoimpl.X.CompressGZIP(file_tai_diaboromon_proto_rawDescData)
	})
	return file_tai_diaboromon_proto_rawDescData
}

var file_tai_diaboromon_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tai_diaboromon_proto_goTypes = []any{
	(*SolicitudAtaque)(nil),    // 0: taidiaboromon.SolicitudAtaque
	(*ConfirmacionAtaque)(nil), // 1: taidiaboromon.ConfirmacionAtaque
	(*SolicitudEstado)(nil),    // 2: taidiaboromon.SolicitudEstado
	(*RespuestaEstado)(nil),    // 3: taidiaboromon.RespuestaEstado
}
var file_tai_diaboromon_proto_depIdxs = []int32{
	0, // 0: taidiaboromon.TaiDiaboromonService.AtaqueDiaboromon:input_type -> taidiaboromon.SolicitudAtaque
	2, // 1: taidiaboromon.TaiDiaboromonService.EstadoVida:input_type -> taidiaboromon.SolicitudEstado
	1, // 2: taidiaboromon.TaiDiaboromonService.AtaqueDiaboromon:output_type -> taidiaboromon.ConfirmacionAtaque
	3, // 3: taidiaboromon.TaiDiaboromonService.EstadoVida:output_type -> taidiaboromon.RespuestaEstado
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tai_diaboromon_proto_init() }
func file_tai_diaboromon_proto_init() {
	if File_tai_diaboromon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tai_diaboromon_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SolicitudAtaque); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tai_diaboromon_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ConfirmacionAtaque); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tai_diaboromon_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SolicitudEstado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tai_diaboromon_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RespuestaEstado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tai_diaboromon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tai_diaboromon_proto_goTypes,
		DependencyIndexes: file_tai_diaboromon_proto_depIdxs,
		MessageInfos:      file_tai_diaboromon_proto_msgTypes,
	}.Build()
	File_tai_diaboromon_proto = out.File
	file_tai_diaboromon_proto_rawDesc = nil
	file_tai_diaboromon_proto_goTypes = nil
	file_tai_diaboromon_proto_depIdxs = nil
}
