version: '3'
services:
  supervisores:
    build: ./supervisores_hexgate
    container_name: container_supervisores
    networks:
      - network_tarea

  broker:
    build: ./broker
    container_name: container_broker
    ports:
      - "50054:50054"
    networks:
      - network_tarea

  # Servidor Hextech 1
  hextech1:
    build: ./servidores_hextech/servidor_1
    container_name: container_hextech1
    networks:
      - network_tarea
    ports:
      - "50051:50051" # Exponiendo el puerto del servidor Hextech 1
    environment:
      - SERVER_ID=1

  # Servidor Hextech 2
  hextech2:
    build: ./servidores_hextech
    container_name: container_hextech2
    networks:
      - network_tarea
    ports:
      - "50052:50052" # Exponiendo el puerto del servidor Hextech 2
    environment:
      - SERVER_ID=2

  # Servidor Hextech 3
  hextech3:
    build: ./servidores_hextech
    container_name: container_hextech3
    networks:
      - network_tarea
    ports:
      - "50053:50053" # Exponiendo el puerto del servidor Hextech 3
    environment:
      - SERVER_ID=3

#Red EXTERNA que se crea mediante docker
networks:
  network_tarea:
    external: true