version: '3'
services:
  supervisores:
    build: ./supervisores_hexgate
    container_name: container_supervisores
    ports:
      - "50053:50053"
    networks:
      - network_tarea
  broker:
    build: ./broker
    container_name: container_broker
    ports:
      - "50054:50054"
    networks:
      - network_tarea
#Red EXTERNA que se crea mediante docker
networks:
  network_tarea:
    external: true