version: '3'
services:
  image_isla_file:
    build: ./servidores_regionales/isla_file
    container_name: container_isla_file
    ports:
      - "50051:50051"
    volumes:
      - ./input.txt:/app/input.txt
    networks:
      - network_tarea
  image_data_node_1:
    build: ./data_nodes/data_node_1
    container_name: container_data_node_1
    ports:
      - "50056:50056"
    networks:
      - network_tarea
  image_continente_folder:
    build: ./servidores_regionales/continente_folder
    container_name: container_continente_folder
    ports:
      - "50057:50057"
    volumes:
      - ./input.txt:/app/input.txt
    networks:
      - network_tarea
  image_diaboromon:
    build: ./diaboromon
    container_name: container_diaboromon
    networks:
      - network_tarea
    ports:
      - "50058:50058"
    volumes:
      - ./input.txt:/app/input.txt
  image_continente_server:
    build: ./servidores_regionales/continente_server
    container_name: container_continente_server
    ports:
      - "50055:50055"
    volumes:
      - ./input.txt:/app/input.txt
    networks:
      - network_tarea
  image_data_node_2:
    build: ./data_nodes/data_node_2
    container_name: container_data_node_2
    ports:
      - "50053:50053"
    networks:
      - network_tarea
  image_primary_node:
    build: ./primary_node
    container_name: container_primary_node
    ports:
      - "50052:50052"    
    networks:
      - network_tarea
  image_nodo_tai:
    build: ./nodo_tai
    container_name: container_nodo_tai
    networks:
      - network_tarea
    ports:
      - "50059:50059"
    volumes:
      - ./input.txt:/app/input.txt
#Red EXTERNA que se crea mediante docker
networks:
  network_tarea:
    external: true