# Comando para iniciar los servicios de la maquina 1: isla_file y data_node_1
docker-MV1:
    	
	@docker-compose -f ./app/docker-compose.yml up image_data_node_1 image_data_node_2

docker-MV2:
    
	@docker-compose -f ./app/docker-compose.yml up image_primary_node image_isla_file

docker-MV3:
    
	@docker-compose -f ./app/docker-compose.yml up image_continente_folder image_continente_server

docker-MV4:
    
	@docker-compose -f ./app/docker-compose.yml up image_nodo_tai image_diaboromon