# Comando para iniciar los servicios de la maquina 1: isla_file y  data_node_1
docker-MV1:

	@docker-compose -f ./app/docker-compose.yml up image_data_node_1
    
	@docker-compose -f ./app/docker-compose.yml up image_data_node_2

docker-MV4:
    
	@docker-compose -f ./app/docker-compose.yml up image_nodo_tai
    
	@docker-compose -f ./app/docker-compose.yml up image_diaboromon

docker-MV3:
    
	@docker-compose -f ./app/docker-compose.yml up image_continente_folder
    
	@docker-compose -f ./app/docker-compose.yml up image_continente_server

docker-MV2:
    
	@docker-compose -f ./app/docker-compose.yml up image_primary_node
    
	@docker-compose -f ./app/docker-compose.yml up image_isla_file