// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: nodo_tai.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodoTaiService_SolicitarDatos_FullMethodName = "/nodotai.NodoTaiService/SolicitarDatos"
	NodoTaiService_RecibirAtaque_FullMethodName  = "/nodotai.NodoTaiService/RecibirAtaque"
)

// NodoTaiServiceClient is the client API for NodoTaiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodoTaiServiceClient interface {
	// RPC para solicitar cantidad de datos al Primary Node
	SolicitarDatos(ctx context.Context, in *Solicitud, opts ...grpc.CallOption) (*Respuesta, error)
	// RPC para recibir ataques de Diaboromon
	RecibirAtaque(ctx context.Context, in *AtaqueDiaboromon, opts ...grpc.CallOption) (*Respuesta, error)
}

type nodoTaiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodoTaiServiceClient(cc grpc.ClientConnInterface) NodoTaiServiceClient {
	return &nodoTaiServiceClient{cc}
}

func (c *nodoTaiServiceClient) SolicitarDatos(ctx context.Context, in *Solicitud, opts ...grpc.CallOption) (*Respuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, NodoTaiService_SolicitarDatos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodoTaiServiceClient) RecibirAtaque(ctx context.Context, in *AtaqueDiaboromon, opts ...grpc.CallOption) (*Respuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, NodoTaiService_RecibirAtaque_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodoTaiServiceServer is the server API for NodoTaiService service.
// All implementations must embed UnimplementedNodoTaiServiceServer
// for forward compatibility.
type NodoTaiServiceServer interface {
	// RPC para solicitar cantidad de datos al Primary Node
	SolicitarDatos(context.Context, *Solicitud) (*Respuesta, error)
	// RPC para recibir ataques de Diaboromon
	RecibirAtaque(context.Context, *AtaqueDiaboromon) (*Respuesta, error)
	mustEmbedUnimplementedNodoTaiServiceServer()
}

// UnimplementedNodoTaiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodoTaiServiceServer struct{}

func (UnimplementedNodoTaiServiceServer) SolicitarDatos(context.Context, *Solicitud) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarDatos not implemented")
}
func (UnimplementedNodoTaiServiceServer) RecibirAtaque(context.Context, *AtaqueDiaboromon) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecibirAtaque not implemented")
}
func (UnimplementedNodoTaiServiceServer) mustEmbedUnimplementedNodoTaiServiceServer() {}
func (UnimplementedNodoTaiServiceServer) testEmbeddedByValue()                        {}

// UnsafeNodoTaiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodoTaiServiceServer will
// result in compilation errors.
type UnsafeNodoTaiServiceServer interface {
	mustEmbedUnimplementedNodoTaiServiceServer()
}

func RegisterNodoTaiServiceServer(s grpc.ServiceRegistrar, srv NodoTaiServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodoTaiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodoTaiService_ServiceDesc, srv)
}

func _NodoTaiService_SolicitarDatos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solicitud)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodoTaiServiceServer).SolicitarDatos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodoTaiService_SolicitarDatos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodoTaiServiceServer).SolicitarDatos(ctx, req.(*Solicitud))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodoTaiService_RecibirAtaque_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AtaqueDiaboromon)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodoTaiServiceServer).RecibirAtaque(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodoTaiService_RecibirAtaque_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodoTaiServiceServer).RecibirAtaque(ctx, req.(*AtaqueDiaboromon))
	}
	return interceptor(ctx, in, info, handler)
}

// NodoTaiService_ServiceDesc is the grpc.ServiceDesc for NodoTaiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodoTaiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodotai.NodoTaiService",
	HandlerType: (*NodoTaiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SolicitarDatos",
			Handler:    _NodoTaiService_SolicitarDatos_Handler,
		},
		{
			MethodName: "RecibirAtaque",
			Handler:    _NodoTaiService_RecibirAtaque_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodo_tai.proto",
}
