// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: nodo_tai.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensaje de solicitud para pedir datos
type Solicitud struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"` // Mensaje de solicitud
}

func (x *Solicitud) Reset() {
	*x = Solicitud{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodo_tai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Solicitud) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solicitud) ProtoMessage() {}

func (x *Solicitud) ProtoReflect() protoreflect.Message {
	mi := &file_nodo_tai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solicitud.ProtoReflect.Descriptor instead.
func (*Solicitud) Descriptor() ([]byte, []int) {
	return file_nodo_tai_proto_rawDescGZIP(), []int{0}
}

func (x *Solicitud) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// Mensaje de respuesta con cantidad de datos acumulados
type Respuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CantidadDatos float32 `protobuf:"fixed32,1,opt,name=cantidad_datos,json=cantidadDatos,proto3" json:"cantidad_datos,omitempty"` // Cantidad de datos acumulados
}

func (x *Respuesta) Reset() {
	*x = Respuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodo_tai_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta) ProtoMessage() {}

func (x *Respuesta) ProtoReflect() protoreflect.Message {
	mi := &file_nodo_tai_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta.ProtoReflect.Descriptor instead.
func (*Respuesta) Descriptor() ([]byte, []int) {
	return file_nodo_tai_proto_rawDescGZIP(), []int{1}
}

func (x *Respuesta) GetCantidadDatos() float32 {
	if x != nil {
		return x.CantidadDatos
	}
	return 0
}

// Mensaje de ataque de Diaboromon
type AtaqueDiaboromon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dano int32 `protobuf:"varint,1,opt,name=dano,proto3" json:"dano,omitempty"` // Cantidad de daño infligido
}

func (x *AtaqueDiaboromon) Reset() {
	*x = AtaqueDiaboromon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodo_tai_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtaqueDiaboromon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtaqueDiaboromon) ProtoMessage() {}

func (x *AtaqueDiaboromon) ProtoReflect() protoreflect.Message {
	mi := &file_nodo_tai_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtaqueDiaboromon.ProtoReflect.Descriptor instead.
func (*AtaqueDiaboromon) Descriptor() ([]byte, []int) {
	return file_nodo_tai_proto_rawDescGZIP(), []int{2}
}

func (x *AtaqueDiaboromon) GetDano() int32 {
	if x != nil {
		return x.Dano
	}
	return 0
}

var File_nodo_tai_proto protoreflect.FileDescriptor

var file_nodo_tai_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6e, 0x6f, 0x64, 0x6f, 0x5f, 0x74, 0x61, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x6e, 0x6f, 0x64, 0x6f, 0x74, 0x61, 0x69, 0x22, 0x25, 0x0a, 0x09, 0x53, 0x6f, 0x6c,
	0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65,
	0x22, 0x32, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x6f, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x63, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x44,
	0x61, 0x74, 0x6f, 0x73, 0x22, 0x26, 0x0a, 0x10, 0x41, 0x74, 0x61, 0x71, 0x75, 0x65, 0x44, 0x69,
	0x61, 0x62, 0x6f, 0x72, 0x6f, 0x6d, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x6e, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64, 0x61, 0x6e, 0x6f, 0x32, 0x8a, 0x01, 0x0a,
	0x0e, 0x4e, 0x6f, 0x64, 0x6f, 0x54, 0x61, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x38, 0x0a, 0x0e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x72, 0x44, 0x61, 0x74, 0x6f,
	0x73, 0x12, 0x12, 0x2e, 0x6e, 0x6f, 0x64, 0x6f, 0x74, 0x61, 0x69, 0x2e, 0x53, 0x6f, 0x6c, 0x69,
	0x63, 0x69, 0x74, 0x75, 0x64, 0x1a, 0x12, 0x2e, 0x6e, 0x6f, 0x64, 0x6f, 0x74, 0x61, 0x69, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x3e, 0x0a, 0x0d, 0x52, 0x65, 0x63,
	0x69, 0x62, 0x69, 0x72, 0x41, 0x74, 0x61, 0x71, 0x75, 0x65, 0x12, 0x19, 0x2e, 0x6e, 0x6f, 0x64,
	0x6f, 0x74, 0x61, 0x69, 0x2e, 0x41, 0x74, 0x61, 0x71, 0x75, 0x65, 0x44, 0x69, 0x61, 0x62, 0x6f,
	0x72, 0x6f, 0x6d, 0x6f, 0x6e, 0x1a, 0x12, 0x2e, 0x6e, 0x6f, 0x64, 0x6f, 0x74, 0x61, 0x69, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nodo_tai_proto_rawDescOnce sync.Once
	file_nodo_tai_proto_rawDescData = file_nodo_tai_proto_rawDesc
)

func file_nodo_tai_proto_rawDescGZIP() []byte {
	file_nodo_tai_proto_rawDescOnce.Do(func() {
		file_nodo_tai_proto_rawDescData = protoimpl.X.CompressGZIP(file_nodo_tai_proto_rawDescData)
	})
	return file_nodo_tai_proto_rawDescData
}

var file_nodo_tai_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nodo_tai_proto_goTypes = []any{
	(*Solicitud)(nil),        // 0: nodotai.Solicitud
	(*Respuesta)(nil),        // 1: nodotai.Respuesta
	(*AtaqueDiaboromon)(nil), // 2: nodotai.AtaqueDiaboromon
}
var file_nodo_tai_proto_depIdxs = []int32{
	0, // 0: nodotai.NodoTaiService.SolicitarDatos:input_type -> nodotai.Solicitud
	2, // 1: nodotai.NodoTaiService.RecibirAtaque:input_type -> nodotai.AtaqueDiaboromon
	1, // 2: nodotai.NodoTaiService.SolicitarDatos:output_type -> nodotai.Respuesta
	1, // 3: nodotai.NodoTaiService.RecibirAtaque:output_type -> nodotai.Respuesta
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nodo_tai_proto_init() }
func file_nodo_tai_proto_init() {
	if File_nodo_tai_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nodo_tai_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Solicitud); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodo_tai_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Respuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodo_tai_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AtaqueDiaboromon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nodo_tai_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodo_tai_proto_goTypes,
		DependencyIndexes: file_nodo_tai_proto_depIdxs,
		MessageInfos:      file_nodo_tai_proto_msgTypes,
	}.Build()
	File_nodo_tai_proto = out.File
	file_nodo_tai_proto_rawDesc = nil
	file_nodo_tai_proto_goTypes = nil
	file_nodo_tai_proto_depIdxs = nil
}
